### ISSUE TITLE
Review project architecture.

### ISSUE THREAD

**Issue by DaimyoHub** [UserSupra/snake-v1.0#1]
Hi! it might be interesting to review the architecture of your project, just for the comfort of having a look at it.
No matter how big an open-source project is, it's always interesting to add the bare minimum to make a developer want to contribute.

If you really plan to leave your project like this, I would still advise you to put it under a free license.

Personally, I always force myself to follow this architecture:

```.
├── CMakeLists.txt
├─ .gitignore
├── LICENSE
├── README.md
├── src
│   ├─ include
│   │  └── app
│   │      ├─ other_source.hpp
│   │      └─ some_source.hpp
│   ├─ other_source.cpp
│   └─ some_source.cpp
└── tests
    ├─ other_test.cpp
    └─ some_utest.cpp
```

It's very personal, but it's a fairly common model for small projects. You can adapt it to your needs of course.

**Comment by UserSupra** [comment]
> Hi! it might be interesting to review the architecture of your project, just for the comfort of having a look at it.
> No matter how big an open-source project is, it's always interesting to add the bare minimum to make a developer want to contribute.

Hi :) !
Merci for your feedback. I'm very new here. I haven't the standards yet. I will try to do progress in my repository, in the use of github and even in my codes.
